name: Auto PR Generation

on:
  push:
    branches:
      - 'feature/**'

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Get full history

    - name: Get default branch
      id: default-branch
      run: echo "default_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')" >> $GITHUB_OUTPUT

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install openai

    - name: Generate PR Body
      id: pr-body
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        BASE_BRANCH: origin/${{ steps.default-branch.outputs.default_branch }}
        GITHUB_DEFAULT_BRANCH: ${{ steps.default-branch.outputs.default_branch }}
      run: |
        python utils/pr_generator.py > pr_body.txt
        echo "pr_body<<EOF" >> $GITHUB_OUTPUT
        cat pr_body.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: "Feature: ${{ github.ref_name }}"
        base: ${{ steps.default-branch.outputs.default_branch }}
        branch: ${{ steps.default-branch.outputs.default_branch }}
        body: ${{ steps.pr-body.outputs.pr_body }}
        labels: auto-generated