name: Auto-PR-Body Generator

on:
  pull_request:

permissions:
  contents: read
  repository-projects: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies (for Python packages)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev libffi-dev libssl-dev

      - name: AI powered Automatic PR Body Generation
        uses: jbrocher/auto-pr-body-generator@v0.2.2
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
